### ISSUE TITLE
Workshop plan; topics, ordering, etc.

### ISSUE THREAD

**Issue by gavinsimpson** [eric-pedersen/mgcv-esa-workshop#1]
A rough outline and ordering of topics. This is just my basic off-top-of head idea so I won;t be offended if you don't agree.

I was thinking that the theory with some small examples to illustrate and practice would take the morning (given those are often shorter slots, say up to and including **Model Checking**. The rest is for the PM part with more practical/hands on stuff.
- Introduction
  - what are (generalised) additive models?
  - what are splines?
  - what is penalised regression?
  - Is this where we discuss basis-penalty setup?
- Basic model fitting
  - `s()` and its arguments
  - (What the heck is `k` if you don't specify it?)
  - Intro to some of the main functions.**mgcv** methods people will use later (`gam()`, `anova()`, `summary()`, `plot()`, ...)
- Smooth toolbox
  - Introduce the basic types and variations of smoothers
    - Thinplate splines
    - Cubic splines (& cyclic versions)
    - P-splines
  - 2-d isotropic smoothing via `s()`
  - tensor product smooths
  - smooth-factor interaction (`by` terms)
  - random effects splines
- Model checking
  - `gam.check()`
  - concurvity
  - randomised quantile residuals
  - **using gams for testing nonlinearity in other models**
- Model selection
  - shrinkage via shrinkage smooths
  - shrinkage via `select = TRUE`
  - AIC corrected for estimated smoothness params
  - approximate _p_ values here?
- Extended GLM models
  - Beta regression (`betar`)
  - Tweedie (esp for continuous data with non-constant variance and zeroes)
  - Negative-binomial & ZIP
  - **cox.ph? I think a fair number of ecologists are dealing with this kind of data**
- Extended examples/demos
  - Spatial modelling
  - Time series modelling
  - Spatio-temporal models
  - ~~Location-scale models~~
- Other stuff
  - `type = "lpmatrix"`
  - `paraPen`
  - Markov random fields
  - Functional data
  - ~~**Mixed effect models via gamm4**~~
  - ???

Comment, but also (if you can, if not @eric-pedersen can you make David and I have admin/commit rights to this repo only?) if you want to suggest things for removal, use strikethrough (e.g. `~~text~~` so we can discuss if someone has strong desire to include a topic)?

**Comment by eric-pedersen** [comment]
I added my suggested topics in bold, as it appears that Github doesn't allow text color tags. I like this list. I only suggested removing the location-scale one, as I think it would take a bit long to describe for the time we have (even with a day), as I suspect most people won't have experience with it. If you think we can fit it in, though, I'd have no problem with including it. 

Given your longer experience with this sort of thing, Gavin, I'll defer to you on length needed. I would be fine with an all-day Saturday workshop. 

Also, it would be good to have 1-2 good ecological data sets people in the workshop could easily download and work with for many different analyses. Any thoughts on something useful there? For the time series analysis, we can use the lynx data that comes with R, and safely assume everyone at least has heard of it, but I'm not sure of good ones for spatial or spatio-temporal data. Maybe something from the lter website?

**Comment by dill** [comment]
As usual Gavin's brain is significantly more structured than mine...

I like this list too.

In case it's interesting: [the GAM "theory" slides](http://distancesampling.org/workshops/duke-spatial-2015/slides/5-gams.html) from my recent course.

## Timing

I'm assuming we're talking about 6 August? If so that sounds good. I think given that hefty list, it seems like that amount of time is reasonable.

## Data

The course I just taught at Duke has a [website here](http://distancesampling.org/workshops/duke-spatial-2015/) which has some practical exercises doing spatial modelling. Now, all that's done in my [`dsm`](https://github.com/distancedevelopment/dsm) package, but that's effectively just a wrapper around `mgcv`, so there is an easy option to build something from that (ignoring detectability and other distance sampling stuff).

## Content preferences

I'm not sure I'd go so far as to strike them out, but here are some thoughts. These would be my list of things to cut if we were running short on time (in some kind of order).
- functional data analysis (I know, I suggested it...): probably least useful to ecologists (there is a very cool paper about little auks that I reviewed, but I don't see much else. As much as I'd like to change this, I don't think this is the venue).
- using `gamm`/`gamm4`: I have a very low success rate with getting these to work for me. Perhaps I'm specifying models which are too complex, I'm definitely interested if you have working models!
- P-splines: I like P-splines in theory, I think they are cool. I think they are a good teaching aide too, much simpler than TPRS or even cubic splines. **But** I never use them in practice. Maybe you two have different experiences. Happy to include them if they're part of your usual arsenal :)

## Practicals

I think theory morning, practical afternoon is a good format. Am I right in thinking that we would expect folks to bring their own laptops and that everything would take place in one room? In this case I guess we can do relatively rapid switching between computer and talking. Perhaps an afternoon of mixed case-studies/hands-on makes sense? (Post-lunch energy levels always seem to fluctuate, to switching around a bit can be helpful.)

A comment I've got (perhaps you two have too) is that folks wanted time to work on their own data. I'm generally against this, because it means that instructors end up spending a lot of time (as the overhead from dealing with new data is large) with a few people and it's not fair on the rest of the class. Again, maybe you two have strong opposing opinions on this.

**Comment by eric-pedersen** [comment]
Keeping the same headings (both timing and data sound great):

# Content preferences:
- Functional data: I'd actually advocate for keeping functional data analysis in, at least in terms of using linear functional terms; I've found it to be one of the most useful tools in mgcv (for instance, non-parametric dispersal kernel estimation with multiple possible seed sources), and one of the harder ones for people to learn about from the docs. 
- gamm4: I'm fine with dropping gamm models though. It would be a lot of extra theory, and extra coding syntax. I've had some luck working with them, but it might be better left as something mentioned but not covered.
- P-splines vs. tps or cubics: I'm fine with cutting P-splines. It might be useful to start from cubics to motivate the theory, using glms and the smooth.construct2 function. That way, participants could get a good idea of what basis functions look like.

# Practicals

I've found that for teaching this sort of workshop, it's best to switch between short lectures using scripts and exercises done by the participants, which would mean everyone would need laptops. I think we could have people do some hands on coding even in the morning theory section; I think the best way to learn what a 'basis function' is is for people to see them emerge from the code. 

I'm also generally opposed to people bringing their own data to work on. At worst, it ends up as a data-cleaning session or with people playing around with their own data rather than focusing on the course, and even at best, it means instructors have to spend too much time learning other people's data.

I'm going to start a quick draft of the abstract, then toss it in to the repository as a .md file; I'lll let you both know on here when that's done and ready for comments.

**Comment by dill** [comment]
I'm going to close this at it's superceeded by https://github.com/eric-pedersen/mgcv-esa-workshop/blob/master/course_outline.md, for which I'll open a new issue on timings.
