### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by dill** [eric-pedersen/mgcv-esa-workshop#5]
@eric-pedersen here are some things that we talked about... on the examples:

Could we use the BBS data for the spatial and time series data, so that we did:
- time series at one site
- spatial snapshot at one time

then we don't have to introduce a bunch of different data sets? (Need to check with Dave Harris about modelling this -- ignore detectability.)

Do you have strong feelings about this?

**Comment by eric-pedersen** [comment]
The BBS data sounds good. I'm guessing we'd be working with data on species richness? Or were you thinking data from a single species? 

I think we can safely ignore a bunch of the caveats about how to model this (detectability and such); we'll just have to say that we're not covering a complete course in stats, and there's additional issues we're ignoring here wrt detection effects. 

Also, I could work the BBS data into the functional smooths section; if we can find a couple decent GIS layers that have the same coverage as the spatial BBS data, I could demonstrate how functional smooths could be used to estimate the effects of, say, temperature at different scales.

**Comment by eric-pedersen** [comment]
Does anyone have a clean copy of BBS data around? I played around a bit with their data retrieving app, but we should settle on a definitive copy of the data to upload and if someone has a copy already, that would be really useful.

**Comment by gavinsimpson** [comment]
I'm close, I think. I was using Dave Harris's code from his species interactions paper: http://biorxiv.org/content/early/2015/11/26/018861

**Comment by dill** [comment]
Great!

Agree completely on caveating the analysis -- we're just talking about 
smooths here, we don't care about the rest.

If doing the functional smoothing stuff is feasible that's great, but 
that's still pretty experimental at this point, so I woundn't go crazy 
trying to get something working.

Regarding getting the data, Gavin thought he might get a subset 
using/from Dave Harris' code available on github.

**Comment by eric-pedersen** [comment]
Thanks for tracking down that data, Gavin! That sounds good to me. I was trying to play around a bit on the plane with data from the BBS from Florida, but a clean version from Dave's work would be great.

Re: the functional smoothing: I was being sloppy when writing; I was just thinking of using the linear functional techniques described in `?mgcv::linear.functional.terms`. I think they're useful to cover mostly because I keep finding new uses for them (estimating dispersal kernels, estimating effects at different spatial scales, smoothed auto-regressive models), but that may be because I've learned this particular hammer, and now every problem looks nail-shaped. I'll try and write up a module for them, for the extended examples half of the day.

Also: for the project timeline: I'm going to a conference (CSEE) from the 6th until the 11th, so I may be a bit limited in the time I can put into this until then. I will try to get a template for the "extended examples" section done before then though, so we have something to extend.

**Comment by dill** [comment]
Sounds great to me. It would be cool (if even from only my perspective) 
to put together a showcase of what is possible using those kinds of 
models, as well as a larger worked example.

**Comment by dill** [comment]
Again, I think we're done here.
