### ISSUE TITLE
Equipment 

### ISSUE THREAD

**Issue by dill** [eric-pedersen/mgcv-esa-workshop#7]
If there isn't wifi, should we plan for this problem and bring some USB sticks/drives with CRAN mirrors on or somesuch? Maybe `packrat` can help? I also have a spare wireless router I can bring.

**Comment by gavinsimpson** [comment]
Are we planning on using anything beyond _mgcv_? (Ideally we'd keep those bit to a minimum as even with WiFi they introduce additional points of failure.)

I've never used packrat so can't say, but if it is useful to provide an environment for users if we have no wifi then let's give it a go.

**Comment by gavinsimpson** [comment]
I've asked about wifi for the workshop, but even when we've had it in the past, invariably we've needed local copies of data, packages, materials, R and RStudio etc on USB drives.

**Comment by dill** [comment]
Our potential dependencies package-wise I think are going to be based on 
where we can get data. We can get around this to some degree but 
stockpiling the RData files we need (in this repo?) and credit them 
correctly, thus avoiding the package dependency issue.

The only other obvious thing I can think of is ggplot2, which is (IIRC) 
actually a minor headache when it comes to dependencies (if the R 
installation is fresh) -- it depends on scales, which depends on RCpp... 
I've not done this from scratch in a while though.

**Comment by eric-pedersen** [comment]
I tried to use Packrat a few iterations ago, and didn't have much luck with it, but I imagine it's improved since then. I do agree that the wireless might be an issue, and ggplot2 is pretty essential in my view (especially as a lot of people now seem to only really be familiar with it rather than base plot).

Data should be easy; we can just create a zip file with an R Studio project containing all the data, scripts, and folder structures in it. Then people can just load that zip file and be good to go. For packages, though, we might want to try creating a list of needed packages and try and create a Packrat file, and see if we can successfully load it on a Mac, PC, and Linux machine prior to the actual workshop.

**Comment by dill** [comment]
Okay that sound sensible. The RStudio idea sounds great to me.

re: packrat, I noticed this on their site 
(https://rstudio.github.io/packrat/):

"""
You’ll also need to make sure your machine is able to build packages 
from source. See Package Development Prerequisites for the tools needed 
for your operating system.
"""

So that's probably a nono for most folks.

**Comment by dill** [comment]
Assuming that @gavinsimpson brings USB sticks and Eric brings his phone, (and we all bring our relevant adapaters) I'm closing this.

**Comment by gavinsimpson** [comment]
My USB drives turned up today, so I'll have 4 clean 16GB drives available for use
